/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.CardLayout;
import java.awt.Component;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Encounter;
import model.EncounterHistory;
import model.VitalSigns;
import model.System;

/**
 *
 * @author gunasekhar
 */
public class VitalSignsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form VitalSignsJPanel
     */
    
    private JPanel displayJPanel;
    private VitalSigns vitalSigns;
    
    public VitalSignsJPanel(JPanel displayJPanel, VitalSigns vitalSigns) {
        this.displayJPanel=displayJPanel;
        this.vitalSigns=vitalSigns;
        initComponents();
        displayData(vitalSigns);
    }
    
    private void displayData(VitalSigns vitalSigns){
        
        txtweight.setText(String.valueOf(vitalSigns.getWeight()));
        txtbloodPressureSystolic.setText(String.valueOf(vitalSigns.getBloodPressureSystolic()));
        txtbloodPressureDiastolic.setText(String.valueOf(vitalSigns.getBloodPressureDiastolic()));
        txtheight.setText(String.valueOf(vitalSigns.getHeight()));
        txtbodyTemperature.setText(String.valueOf(vitalSigns.getBodyTemperature()));
        txtpulseRate.setText(String.valueOf(vitalSigns.getPulseRate()));
        txtrespirationRate.setText(String.valueOf(vitalSigns.getRespirationRate()));
        txtoxygenSaturation.setText(String.valueOf(vitalSigns.getOxygenSaturation()));
        lblcreatedonOUT.setText(vitalSigns.getCreatedOn());
        lblupdatedonOUT.setText(vitalSigns.getUpdatedOn());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        vitalSignsJLabel = new javax.swing.JLabel();
        weightJLabel = new javax.swing.JLabel();
        txtweight = new javax.swing.JTextField();
        bloodPressureSystolicJLabel = new javax.swing.JLabel();
        txtbloodPressureSystolic = new javax.swing.JTextField();
        heightJLabel = new javax.swing.JLabel();
        bodyTemperatureJLabel = new javax.swing.JLabel();
        pulseRateJLabel = new javax.swing.JLabel();
        respirationRateJLabel = new javax.swing.JLabel();
        oxygenSaturationJLabel = new javax.swing.JLabel();
        txtheight = new javax.swing.JTextField();
        txtbodyTemperature = new javax.swing.JTextField();
        txtpulseRate = new javax.swing.JTextField();
        txtrespirationRate = new javax.swing.JTextField();
        txtoxygenSaturation = new javax.swing.JTextField();
        updateJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        txtbloodPressureDiastolic = new javax.swing.JTextField();
        bloodPressureDiastolicJLabel = new javax.swing.JLabel();
        lblcreatedon = new javax.swing.JLabel();
        lblcreatedonOUT = new javax.swing.JLabel();
        lblupdatedon = new javax.swing.JLabel();
        lblupdatedonOUT = new javax.swing.JLabel();

        vitalSignsJLabel.setFont(new java.awt.Font("Lucida Grande", 1, 20)); // NOI18N
        vitalSignsJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vitalSignsJLabel.setText("Vital Signs");

        weightJLabel.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        weightJLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        weightJLabel.setText("Weight :");

        bloodPressureSystolicJLabel.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        bloodPressureSystolicJLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        bloodPressureSystolicJLabel.setText("Blood Pressure Systolic :");

        heightJLabel.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        heightJLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        heightJLabel.setText("Height :");

        bodyTemperatureJLabel.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        bodyTemperatureJLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        bodyTemperatureJLabel.setText("Body Temperature :");

        pulseRateJLabel.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        pulseRateJLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        pulseRateJLabel.setText("Pulse Rate :");

        respirationRateJLabel.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        respirationRateJLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        respirationRateJLabel.setText("Respiration Rate :");

        oxygenSaturationJLabel.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        oxygenSaturationJLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        oxygenSaturationJLabel.setText("Oxygen Saturation :");

        updateJButton.setText("Update");
        updateJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateJButtonActionPerformed(evt);
            }
        });

        backJButton.setText("< < Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        bloodPressureDiastolicJLabel.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        bloodPressureDiastolicJLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        bloodPressureDiastolicJLabel.setText("Blood Pressure Diastolic :");

        lblcreatedon.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lblcreatedon.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblcreatedon.setText("Created On :");

        lblcreatedonOUT.setText("h");

        lblupdatedon.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lblupdatedon.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblupdatedon.setText("Updated On :");

        lblupdatedonOUT.setText("h");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(backJButton)
                        .addGap(61, 61, 61)
                        .addComponent(vitalSignsJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(168, 168, 168)
                                .addComponent(updateJButton))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(8, 8, 8)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(heightJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(pulseRateJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(respirationRateJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(1, 1, 1)
                                            .addComponent(bodyTemperatureJLabel))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblcreatedon)
                                            .addComponent(oxygenSaturationJLabel)))
                                    .addGap(82, 82, 82)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtbodyTemperature, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtheight, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtpulseRate, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtrespirationRate, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtoxygenSaturation, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(34, 34, 34)
                                                .addComponent(weightJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(89, 89, 89))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addGap(4, 4, 4)
                                                .addComponent(bloodPressureSystolicJLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(bloodPressureDiastolicJLabel)
                                            .addGap(82, 82, 82)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtbloodPressureDiastolic, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtbloodPressureSystolic, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtweight, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(lblcreatedonOUT)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(85, 85, 85)
                                    .addComponent(lblupdatedon)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblupdatedonOUT))))))
                .addContainerGap(265, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {bodyTemperatureJLabel, heightJLabel, oxygenSaturationJLabel, pulseRateJLabel, respirationRateJLabel, weightJLabel});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblcreatedonOUT, lblupdatedonOUT, txtoxygenSaturation});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vitalSignsJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backJButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtweight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(weightJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bloodPressureSystolicJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtbloodPressureSystolic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bloodPressureDiastolicJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtbloodPressureDiastolic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(heightJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtheight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bodyTemperatureJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtbodyTemperature, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pulseRateJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtpulseRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(respirationRateJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtrespirationRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(oxygenSaturationJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtoxygenSaturation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblcreatedon, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblcreatedonOUT))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblupdatedon, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblupdatedonOUT))
                .addGap(18, 18, 18)
                .addComponent(updateJButton)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblcreatedonOUT, lblupdatedonOUT, txtoxygenSaturation});

    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        displayJPanel.remove(this);
        Component[] componentArray = displayJPanel.getComponents();
        Component component = componentArray[componentArray.length-1];
        EncounterHistoryJPanel encounterHistoryJPanel = (EncounterHistoryJPanel) component;
        encounterHistoryJPanel.populateEncounterHistoryTable();
        CardLayout cardLayout = (CardLayout) displayJPanel.getLayout();
        cardLayout.previous(displayJPanel);
    }//GEN-LAST:event_backJButtonActionPerformed
    private String formatDate(Date date){

        String pattern = "yyyy-MM-dd HH:mm:ss";
        SimpleDateFormat simpleDateFormat = new SimpleDateFormat(pattern);
        return simpleDateFormat.format(date);
    }
    
    private void updateJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateJButtonActionPerformed
//        VitalSigns vitalSigns = new VitalSigns();
        boolean success = false;
        try {
            double bodyTemperature = Double.parseDouble(txtbodyTemperature.getText());
            vitalSigns.setBodyTemperature(bodyTemperature);
            success = true;            
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(null, "Body Temperature must be a Float decimal number");
            success = false;
        }

        try {
            int pulse = Integer.parseInt(txtpulseRate.getText());
            vitalSigns.setPulseRate(pulse);
            success = true;
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(null, "Pulse Rate must be an Integer");
            success = false;
        }

        try {
            double bloodPressureSystolic = Double.parseDouble(txtbloodPressureSystolic.getText());
            vitalSigns.setBloodPressureSystolic(bloodPressureSystolic);
            success = true;
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(null, "Systolic BP must be a Float decimal number");
            success = false;
        }

        try {
            double bloodPressureDiastolic = Double.parseDouble(txtbloodPressureDiastolic.getText());
            vitalSigns.setBloodPressureDiastolic(bloodPressureDiastolic);
            success = true;
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(null, "Diastolic Blood Pressure must be a Float decimal number");
            success = false;
        }

        try {
            int respirationRate = Integer.parseInt(txtrespirationRate.getText());
            vitalSigns.setRespirationRate(respirationRate);
            success = true;
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(null, "Respiration Rate must be an Integer"); 
            success = false;
        }

        try {
            double height = Double.parseDouble(txtheight.getText());
            vitalSigns.setHeight(height);
            success = true;
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(null, "Height must be a Float decimal number"); 
            success = false;
        }

        try {
            double oxygenSaturation = Double.parseDouble(txtoxygenSaturation.getText());
            vitalSigns.setOxygenSaturation(oxygenSaturation);
            success = true;
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(null, "Oxygen Saturation must be a Double decimal number"); 
            success = false;
        }
        
        try {
            double weight = Double.parseDouble(txtweight.getText());
            vitalSigns.setWeight(weight);
            success = true;
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(null, "Weight must be a Float decimal number"); 
            success = false;
        }
        
        if (success) {
            vitalSigns.setUpdatedOn(formatDate(new Date()));

            vitalSigns.setWeight(Double.valueOf(txtweight.getText()));
            vitalSigns.setBloodPressureSystolic(Double.valueOf(txtbloodPressureSystolic.getText()));
            vitalSigns.setBloodPressureDiastolic(Double.valueOf(txtbloodPressureDiastolic.getText()));
            vitalSigns.setHeight(Double.valueOf(txtheight.getText()));
            vitalSigns.setBodyTemperature(Double.valueOf(txtbodyTemperature.getText()));
            vitalSigns.setPulseRate(Integer.valueOf(txtpulseRate.getText()));
            vitalSigns.setRespirationRate(Integer.valueOf(txtrespirationRate.getText()));
            vitalSigns.setOxygenSaturation(Double.valueOf(txtoxygenSaturation.getText()));
            
            JOptionPane.showMessageDialog(this, "Successfully updated the Vital Signs");
            resetData();

        }
            
//                        Encounter encounter = new Encounter(vitalSigns);
// 
//            EncounterHistory encounterHistory = person.getPatient().getEncounterHistory();
//            encounterHistory.getEncounterHistory().add(encounter);
    }//GEN-LAST:event_updateJButtonActionPerformed

    private void resetData(){
        
        txtbloodPressureSystolic.setText("");
        txtbloodPressureDiastolic.setText("");
        txtbodyTemperature.setText("");
        txtheight.setText("");
        txtoxygenSaturation.setText("");
        txtpulseRate.setText("");
        txtrespirationRate.setText("");
        txtweight.setText("");
        lblcreatedonOUT.setText("");
        lblupdatedonOUT.setText("");
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel bloodPressureDiastolicJLabel;
    private javax.swing.JLabel bloodPressureSystolicJLabel;
    private javax.swing.JLabel bodyTemperatureJLabel;
    private javax.swing.JLabel heightJLabel;
    private javax.swing.JLabel lblcreatedon;
    private javax.swing.JLabel lblcreatedonOUT;
    private javax.swing.JLabel lblupdatedon;
    private javax.swing.JLabel lblupdatedonOUT;
    private javax.swing.JLabel oxygenSaturationJLabel;
    private javax.swing.JLabel pulseRateJLabel;
    private javax.swing.JLabel respirationRateJLabel;
    private javax.swing.JTextField txtbloodPressureDiastolic;
    private javax.swing.JTextField txtbloodPressureSystolic;
    private javax.swing.JTextField txtbodyTemperature;
    private javax.swing.JTextField txtheight;
    private javax.swing.JTextField txtoxygenSaturation;
    private javax.swing.JTextField txtpulseRate;
    private javax.swing.JTextField txtrespirationRate;
    private javax.swing.JTextField txtweight;
    private javax.swing.JButton updateJButton;
    private javax.swing.JLabel vitalSignsJLabel;
    private javax.swing.JLabel weightJLabel;
    // End of variables declaration//GEN-END:variables
}
